name: APPROVE

on: pull_request

permissions:
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number}}/reviews \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          -d '{"event":"APPROVE"}'